### ISSUE TITLE
Дополнить правила именования файлов

### ISSUE THREAD

**Issue by ierhyna** [andrey-hohlov/psd-templates-requirements#2]
> Название файлов и слоёв писать по-английски или транслитом. К названиям файлов добавлять приставки, позволяющие легко определить актуальную версию. Например, file-1.psd или file-final.psd.

Лучше писать дату в формате год-месяц-число, например, file_2016-11-01.psd, а если макет согласуется несколько раз в день, то и время.
Иначе потом начинается - `file-final51.psd`, `file-final-last.psd`, `file-last-final.psd`

**Comment by andrey-hohlov** [comment]
Согласен. Сделаете PR или сам допишу?

**Comment by ierhyna** [comment]
Сделаю PR сегодня.
